-- =========================================================
-- ROLES
-- =========================================================
CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias       VARCHAR(100),
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),

    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,

    CONSTRAINT uq_roles_name UNIQUE (name)
);

-- =========================================================
-- PERMISSIONS
-- =========================================================
CREATE TABLE permissions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module      VARCHAR(100) NOT NULL,
    action      VARCHAR(100) NOT NULL,
    description VARCHAR(255),

    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,

    CONSTRAINT uq_permissions_module_action UNIQUE (module, action)
);

-- =========================================================
-- USERS
-- =========================================================
CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identification VARCHAR(50)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    first_name     VARCHAR(100),
    password       VARCHAR(255) NOT NULL,
    email          VARCHAR(150) NOT NULL,
    phone          VARCHAR(30),
    user_registry  VARCHAR(100) NOT NULL,

    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP,

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_user_registry UNIQUE (user_registry),
    CONSTRAINT uq_users_identification UNIQUE (identification)
);