-- =========================================================
-- USERS
-- =========================================================

CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identification VARCHAR(13) UNIQUE,
    name           VARCHAR(100),
    first_name     VARCHAR(100),
    user_registry  VARCHAR(80) UNIQUE,
    phone          VARCHAR(20),
    password       VARCHAR(255),
    email          VARCHAR(150) UNIQUE,
    status         BOOLEAN     NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ
);

-- Intermediate table of roles and users
CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
            ON DELETE CASCADE
);