-- =========================================================
-- CLIENTS
-- =========================================================
CREATE TABLE clients
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dpi        VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(100),
    last_name  VARCHAR(100),
    email      VARCHAR(150),
    phone      VARCHAR(30),
    address    VARCHAR(255),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- =========================================================
-- PET
-- =========================================================
CREATE TABLE pet
(
    id_pet      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100),
    breed       VARCHAR(100),
    id_client   BIGINT           NOT NULL,
    color       VARCHAR(50),
    age         INT              NOT NULL,
    weight      DOUBLE PRECISION NOT NULL,
    species     VARCHAR(50),
    description VARCHAR(255),

    created_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,

    CONSTRAINT fk_pet_client
        FOREIGN KEY (id_client) REFERENCES clients (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_pet_id_client ON pet (id_client);