CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    room_id BIGINT,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    description VARCHAR(255) NOT NULL,
    diagnosis TEXT,
    status VARCHAR(50) DEFAULT 'SCHEDULED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_appointments_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_appointments_pet FOREIGN KEY (pet_id) REFERENCES  pets (id_pet) ON DELETE CASCADE,
    CONSTRAINT fk_appointments_room FOREIGN KEY (room_id) REFERENCES rooms (id)
);
